export const GET_USERS = 'GET_USERS';
export const SET_NEW_CHAT = 'SET_NEW_CHAT';
export const GET_CHATS = 'GET_CHATS';
export const CLEAR_SELECTED_USERS = 'CLEAR_SELECTED_USERS';
export const PUSH_SELECTED_USERS = 'PUSH_SELECTED_USERS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
