export const SET_MESSAGES = 'SET_MESSAGES';
export const SET_COMPANION_DATA = 'SET_COMPANION_DATA';
export const SET_NEW_MESSAGE = 'SET_NEW_MESSAGE';
export const CLEAR_COMPANION_STORE = 'CLEAR_COMPANION_STORE';
export const CLEAR_MESSAGE_STORE = 'CLEAR_MESSAGE_STORE';
export const SET_NEW_MESSAGE_STAMP = 'SET_NEW_MESSAGE_STAMP';
